/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package scala_app3

// import org.apache.spark.{SparkConf, SparkContext}
import org.apache.spark.sql.SparkSession

object App {
  
  def main(args: Array[String]): Unit = {
    val spark = SparkSession.builder.appName("Simple Application").config("spark.master", "local").getOrCreate()
    val logFile = "/Users/paulhechinger/spark-3.2.1-bin-hadoop3.2/README.md" // Should be some file on your system

    val logData = spark.read.textFile(logFile).cache()
    val numAs = logData.filter(line => line.contains("a")).count()
    val numBs = logData.filter(line => line.contains("b")).count()
    println(s"Lines with a: $numAs, Lines with b: $numBs")
    spark.stop()
    println(greeting())
  }

  def greeting(): String = "Hello, world!"


 // spark-submit --class scala_app3.App app/build/libs/app.jar

}
