/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
// package scala_app4

// object OldApp {
//   def main(args: Array[String]): Unit = {
//     println(greeting())
//   }

//   def greeting(): String = "Hello, world!"
// }
